---
spring:
  datasource:
    username: "sa"
    url: "jdbc:h2:mem:riga;DATABASE_TO_LOWER=TRUE"
    driverClassName: "org.h2.Driver"
    password: ""
  jpa:
    hibernate:
      ddl-auto: "create"
server:
  port: 18880
management:
  server:
    port: 18081
