# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.28.0
  hooks:
    - id: gitleaks
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.5.0
  hooks:
    - id: sqlfluff-fix
      args: ["--dialect", "postgres", '-e', 'references.keywords']
    - id: sqlfluff-lint
      args: ["--dialect", "postgres", '-e', 'references.keywords']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-case-conflict
    - id: check-illegal-windows-names
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: check-merge-conflict
    - id: no-commit-to-branch
      args: ["--branch", "main", "--branch", "master"]
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.4
    hooks:
    -   id: maven-spotless-apply
